### ISSUE TITLE
cannot find module for path crypto/ed25519

### ISSUE THREAD

**Issue by toellbe** [RightToPrivacy/snowflake-tor-service#1]
Installation fails with

build git.torproject.org/pluggable-transports/snowflake.git/v2/proxy: cannot find module for path crypto/ed25519
FAILED TO BUILD SNOWFLAKE PROXY SOURCE. DO YOU HAVE GOLANG?

golang is installed: 2:1.11~1+b6

**Comment by RightToPrivacy** [comment]
Need 1.13 or greater to run Tor Snowflake Proxy. See if you can upgrade. I'll add GOLANG 1.13 to the message to clear things up. Thanks for reporting your issue. If your system doesn't have a more recent Golang, you can get it at: https://golang.org/dl/

Source: http://xmrhfasfg5suueegrnc4gsgyi2tyclcy5oz7f5drnrodmdtob6t2ioyd.onion/relay/setup/snowflake/standalone/index.html (official Tor onion on standalone snowflake)

**Comment by RightToPrivacy** [comment]
Did upgrading Golang fix this problem for you?
