### ISSUE TITLE
git.torproject.org is not accessible.

### ISSUE THREAD

**Issue by amirHossein5** [RightToPrivacy/snowflake-tor-service#2]
> go version go1.18.7

It fails when tries to clone repo from https://git.torproject.org , because it's not accessible here.

```
Cloning into 'snowflake'...
fatal: unable to access 'https://git.torproject.org/pluggable-transports/snowflake.git/': Failed to connect to git.torproject.org port 443 after 143285 ms: Connection timed out
install.sh: line 76: cd: snowflake/proxy: No such file or directory
```

So i use tor via proxychains to clone it, and it will be clone successfully, but `go build` doesn't work with tor:

```
go: gitlab.torproject.org/tpo/anti-censorship/geoip@v0.0.0-20210928150955-7ce4b3d98d01: unrecognized import path "gitlab.torproject.org/tpo/anti-censorship/geoip": https fetch: Get "https://gitlab.torproject.org/tpo/anti-censorship/geoip?go-get=1": dial tcp 10.10.34.35:443: i/o timeout
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: gitlab.torproject.org/tpo/anti-censorship/geoip@v0.0.0-20210928150955-7ce4b3d98d01: unrecognized import path "gitlab.torproject.org/tpo/anti-censorship/geoip": https fetch: Get "https://gitlab.torproject.org/tpo/anti-censorship/geoip?go-get=1": dial tcp 10.10.34.35:443: i/o timeout
```

also when I try to use `go build` wihtout tor:

```
go: gitlab.torproject.org/tpo/anti-censorship/geoip@v0.0.0-20210928150955-7ce4b3d98d01: unrecognized import path "gitlab.torproject.org/tpo/anti-censorship/geoip": https fetch: Get "https://gitlab.torproject.org/tpo/anti-censorship/geoip?go-get=1": dial tcp 10.10.34.35:443: i/o timeout
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: gitlab.torproject.org/tpo/anti-censorship/geoip@v0.0.0-20210928150955-7ce4b3d98d01: unrecognized import path "gitlab.torproject.org/tpo/anti-censorship/geoip": https fetch: Get "https://gitlab.torproject.org/tpo/anti-censorship/geoip?go-get=1": dial tcp 10.10.34.35:443: i/o timeout
```

any solution for `go build` to use tor?

**Comment by RightToPrivacy** [comment]
Looks to be network error related (due to blocking you mention). 

Proxychains fails to torify certain apps/commands.

If this is case (and your network connection requires tor), one option: something more forceful about torification that uses temp systemwide firewall routing (like anonsurf, torctl quickest to setup). 

In cases where proxychains fails, these work for torifying entire system, long as you can get tor client connected to Tor. 

Can turn them off easily after finished.

That's my initial thought (potential solution for proxychins failing). 

Hope it works for you.

**Comment by amirHossein5** [comment]
Thanks for suggesting anonsurf, torctl, but I couldn't setup them...

Then I was searching for a way to use snowflake from the tor-browser(have tor-browser with snowflake which works great) on terminal version of tor. 
I read some where that I have to copy the torrc file of tor-browser to `/etc/tor/torrc`, but didn't work(permission denied, error related user permissions, dir not found, ....), after lots of tries by changing keys of `/etc/tor/torrc` I couldn't find a way to ues it.

Finally I noticed from log file of tor-browser that it's running on `127.0.0.1:9150`, so added it to system proxy to use it system wide, and then I can use snowflake of tor-browser without configuring, or installing it.

But there's just one problem that I have to remain tor-browser open to use its port.
